// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/label.proto

package label

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LabelDescriptor with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LabelDescriptor) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LabelDescriptor with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LabelDescriptorMultiError, or nil if none found.
func (m *LabelDescriptor) ValidateAll() error {
	return m.validate(true)
}

func (m *LabelDescriptor) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for ValueType

	// no validation rules for Description

	if len(errors) > 0 {
		return LabelDescriptorMultiError(errors)
	}

	return nil
}

// LabelDescriptorMultiError is an error wrapping multiple validation errors
// returned by LabelDescriptor.ValidateAll() if the designated constraints
// aren't met.
type LabelDescriptorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LabelDescriptorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LabelDescriptorMultiError) AllErrors() []error { return m }

// LabelDescriptorValidationError is the validation error returned by
// LabelDescriptor.Validate if the designated constraints aren't met.
type LabelDescriptorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LabelDescriptorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LabelDescriptorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LabelDescriptorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LabelDescriptorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LabelDescriptorValidationError) ErrorName() string { return "LabelDescriptorValidationError" }

// Error satisfies the builtin error interface
func (e LabelDescriptorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLabelDescriptor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LabelDescriptorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LabelDescriptorValidationError{}
