package store

import mock "github.com/stretchr/testify/mock"

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: obj
func (_m *MockValidator) Validate(obj interface{}) error {
	ret := _m.Called(obj)

	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		return rf(obj)
	}

	return ret.Error(0)
}
