# 全局配置
global:
  # 必填，通常使用 Production 或 Development
  namespace: Production
  # 选填，环境名称 test formal
  env_name: formal

http:
  addr: 127.0.0.1:8849


# jwt
jwt:
  public_key: 'LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBb2tHS1g4SkNoN1V2NWovZkFWOUcKRWJFUU5jSWdxOSt0cllEYzBrVDNPenBlQmdoUXhRZTJ2UXdMVnZqb3VjNVNGVTdXbGFLKysyZUJRQzg3RmZUdQpQUjZ5TFpFNE1nMVNJZURpRGpvU3MwaHduaHcvVzhMK0ozQ1VNbkR3cEJZUDhWSkFBYmR0eWF3VW9qckd5ZjBRCnJXUTFtV0tGeWdFMzRNQThrQ1Fka0l4WnlXWXlJNmo0RzFtbm1JZFZqUDF2WVMrMWhoam8vcERxbE1MVkgweFYKV3pJYmFrSE55b09lOUUwWFhlMzVPWVV6UUpwc0R5dy9DMU1EWGw2ZkJKbTJ1SU1KZVFvZDMvK2xOVkd4YTY3QwpWYk1EWStiRHM5VkJFZVVDOXdENDhOU2MrNitJSldzTW11V0VCS25talBhTm04czdjamJzRTB0MSs1RHp4UEdVCll3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K'