// Code generated by trpc-go/trpc-cmdline v1.0.6. DO NOT EDIT.
// source: blog/v1/blog.proto

package api

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// BlogApiService defines service.
type BlogApiService interface {
	// SearchArticle 文章搜索
	SearchArticle(ctx context.Context, req *SearchArticleReq) (*SearchArticleRsp, error)
	// AddOrUpdateArticle 添加修改文章
	AddOrUpdateArticle(ctx context.Context, req *AddOrUpdateArticleReq) (*AddOrUpdateRsp, error)
	// DeleteArticle 删除文章
	DeleteArticle(ctx context.Context, req *DeleteArticleReq) (*EmptyRsp, error)
	// ArticleDetail 文章详情
	ArticleDetail(ctx context.Context, req *ArticleDetailReq) (*Article, error)
}

func BlogApiService_SearchArticle_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SearchArticleReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BlogApiService).SearchArticle(ctx, reqbody.(*SearchArticleReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BlogApiService_AddOrUpdateArticle_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddOrUpdateArticleReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BlogApiService).AddOrUpdateArticle(ctx, reqbody.(*AddOrUpdateArticleReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BlogApiService_DeleteArticle_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteArticleReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BlogApiService).DeleteArticle(ctx, reqbody.(*DeleteArticleReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BlogApiService_ArticleDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ArticleDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BlogApiService).ArticleDetail(ctx, reqbody.(*ArticleDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// BlogApiServer_ServiceDesc descriptor for server.RegisterService.
var BlogApiServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "go_blog.blog.BlogApi",
	HandlerType: ((*BlogApiService)(nil)),
	Methods: []server.Method{
		{
			Name: "/go_blog.blog.BlogApi/SearchArticle",
			Func: BlogApiService_SearchArticle_Handler,
		},
		{
			Name: "/go_blog.blog.BlogApi/AddOrUpdateArticle",
			Func: BlogApiService_AddOrUpdateArticle_Handler,
		},
		{
			Name: "/go_blog.blog.BlogApi/DeleteArticle",
			Func: BlogApiService_DeleteArticle_Handler,
		},
		{
			Name: "/go_blog.blog.BlogApi/ArticleDetail",
			Func: BlogApiService_ArticleDetail_Handler,
		},
	},
}

// RegisterBlogApiService registers service.
func RegisterBlogApiService(s server.Service, svr BlogApiService) {
	if err := s.Register(&BlogApiServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("BlogApi register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedBlogApi struct{}

// SearchArticle 文章搜索
func (s *UnimplementedBlogApi) SearchArticle(ctx context.Context, req *SearchArticleReq) (*SearchArticleRsp, error) {
	return nil, errors.New("rpc SearchArticle of service BlogApi is not implemented")
}

// AddOrUpdateArticle 添加修改文章
func (s *UnimplementedBlogApi) AddOrUpdateArticle(ctx context.Context, req *AddOrUpdateArticleReq) (*AddOrUpdateRsp, error) {
	return nil, errors.New("rpc AddOrUpdateArticle of service BlogApi is not implemented")
}

// DeleteArticle 删除文章
func (s *UnimplementedBlogApi) DeleteArticle(ctx context.Context, req *DeleteArticleReq) (*EmptyRsp, error) {
	return nil, errors.New("rpc DeleteArticle of service BlogApi is not implemented")
}

// ArticleDetail 文章详情
func (s *UnimplementedBlogApi) ArticleDetail(ctx context.Context, req *ArticleDetailReq) (*Article, error) {
	return nil, errors.New("rpc ArticleDetail of service BlogApi is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// BlogApiClientProxy defines service client proxy
type BlogApiClientProxy interface {
	// SearchArticle 文章搜索
	SearchArticle(ctx context.Context, req *SearchArticleReq, opts ...client.Option) (rsp *SearchArticleRsp, err error)
	// AddOrUpdateArticle 添加修改文章
	AddOrUpdateArticle(ctx context.Context, req *AddOrUpdateArticleReq, opts ...client.Option) (rsp *AddOrUpdateRsp, err error)
	// DeleteArticle 删除文章
	DeleteArticle(ctx context.Context, req *DeleteArticleReq, opts ...client.Option) (rsp *EmptyRsp, err error)
	// ArticleDetail 文章详情
	ArticleDetail(ctx context.Context, req *ArticleDetailReq, opts ...client.Option) (rsp *Article, err error)
}

type BlogApiClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewBlogApiClientProxy = func(opts ...client.Option) BlogApiClientProxy {
	return &BlogApiClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *BlogApiClientProxyImpl) SearchArticle(ctx context.Context, req *SearchArticleReq, opts ...client.Option) (*SearchArticleRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/go_blog.blog.BlogApi/SearchArticle")
	msg.WithCalleeServiceName(BlogApiServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("BlogApi")
	msg.WithCalleeMethod("SearchArticle")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SearchArticleRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BlogApiClientProxyImpl) AddOrUpdateArticle(ctx context.Context, req *AddOrUpdateArticleReq, opts ...client.Option) (*AddOrUpdateRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/go_blog.blog.BlogApi/AddOrUpdateArticle")
	msg.WithCalleeServiceName(BlogApiServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("BlogApi")
	msg.WithCalleeMethod("AddOrUpdateArticle")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AddOrUpdateRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BlogApiClientProxyImpl) DeleteArticle(ctx context.Context, req *DeleteArticleReq, opts ...client.Option) (*EmptyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/go_blog.blog.BlogApi/DeleteArticle")
	msg.WithCalleeServiceName(BlogApiServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("BlogApi")
	msg.WithCalleeMethod("DeleteArticle")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &EmptyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BlogApiClientProxyImpl) ArticleDetail(ctx context.Context, req *ArticleDetailReq, opts ...client.Option) (*Article, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/go_blog.blog.BlogApi/ArticleDetail")
	msg.WithCalleeServiceName(BlogApiServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("BlogApi")
	msg.WithCalleeMethod("ArticleDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &Article{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
