// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/config_change.proto

package configchange

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConfigChange with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConfigChange) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfigChange with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConfigChangeMultiError, or
// nil if none found.
func (m *ConfigChange) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfigChange) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Element

	// no validation rules for OldValue

	// no validation rules for NewValue

	// no validation rules for ChangeType

	for idx, item := range m.GetAdvices() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConfigChangeValidationError{
						field:  fmt.Sprintf("Advices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConfigChangeValidationError{
						field:  fmt.Sprintf("Advices[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConfigChangeValidationError{
					field:  fmt.Sprintf("Advices[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ConfigChangeMultiError(errors)
	}

	return nil
}

// ConfigChangeMultiError is an error wrapping multiple validation errors
// returned by ConfigChange.ValidateAll() if the designated constraints aren't met.
type ConfigChangeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfigChangeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfigChangeMultiError) AllErrors() []error { return m }

// ConfigChangeValidationError is the validation error returned by
// ConfigChange.Validate if the designated constraints aren't met.
type ConfigChangeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfigChangeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfigChangeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfigChangeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfigChangeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfigChangeValidationError) ErrorName() string { return "ConfigChangeValidationError" }

// Error satisfies the builtin error interface
func (e ConfigChangeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfigChange.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfigChangeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfigChangeValidationError{}

// Validate checks the field values on Advice with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Advice) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Advice with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AdviceMultiError, or nil if none found.
func (m *Advice) ValidateAll() error {
	return m.validate(true)
}

func (m *Advice) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Description

	if len(errors) > 0 {
		return AdviceMultiError(errors)
	}

	return nil
}

// AdviceMultiError is an error wrapping multiple validation errors returned by
// Advice.ValidateAll() if the designated constraints aren't met.
type AdviceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdviceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdviceMultiError) AllErrors() []error { return m }

// AdviceValidationError is the validation error returned by Advice.Validate if
// the designated constraints aren't met.
type AdviceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdviceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdviceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdviceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdviceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdviceValidationError) ErrorName() string { return "AdviceValidationError" }

// Error satisfies the builtin error interface
func (e AdviceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdvice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdviceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdviceValidationError{}
