// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/billing.proto

package serviceconfig

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Billing with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Billing) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Billing with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BillingMultiError, or nil if none found.
func (m *Billing) ValidateAll() error {
	return m.validate(true)
}

func (m *Billing) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetConsumerDestinations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BillingValidationError{
						field:  fmt.Sprintf("ConsumerDestinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BillingValidationError{
						field:  fmt.Sprintf("ConsumerDestinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BillingValidationError{
					field:  fmt.Sprintf("ConsumerDestinations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BillingMultiError(errors)
	}

	return nil
}

// BillingMultiError is an error wrapping multiple validation errors returned
// by Billing.ValidateAll() if the designated constraints aren't met.
type BillingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BillingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BillingMultiError) AllErrors() []error { return m }

// BillingValidationError is the validation error returned by Billing.Validate
// if the designated constraints aren't met.
type BillingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BillingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BillingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BillingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BillingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BillingValidationError) ErrorName() string { return "BillingValidationError" }

// Error satisfies the builtin error interface
func (e BillingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBilling.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BillingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BillingValidationError{}

// Validate checks the field values on Billing_BillingDestination with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Billing_BillingDestination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Billing_BillingDestination with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Billing_BillingDestinationMultiError, or nil if none found.
func (m *Billing_BillingDestination) ValidateAll() error {
	return m.validate(true)
}

func (m *Billing_BillingDestination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MonitoredResource

	if len(errors) > 0 {
		return Billing_BillingDestinationMultiError(errors)
	}

	return nil
}

// Billing_BillingDestinationMultiError is an error wrapping multiple
// validation errors returned by Billing_BillingDestination.ValidateAll() if
// the designated constraints aren't met.
type Billing_BillingDestinationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Billing_BillingDestinationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Billing_BillingDestinationMultiError) AllErrors() []error { return m }

// Billing_BillingDestinationValidationError is the validation error returned
// by Billing_BillingDestination.Validate if the designated constraints aren't met.
type Billing_BillingDestinationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Billing_BillingDestinationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Billing_BillingDestinationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Billing_BillingDestinationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Billing_BillingDestinationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Billing_BillingDestinationValidationError) ErrorName() string {
	return "Billing_BillingDestinationValidationError"
}

// Error satisfies the builtin error interface
func (e Billing_BillingDestinationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBilling_BillingDestination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Billing_BillingDestinationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Billing_BillingDestinationValidationError{}
