// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/monitoring.proto

package serviceconfig

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Monitoring with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Monitoring) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Monitoring with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MonitoringMultiError, or
// nil if none found.
func (m *Monitoring) ValidateAll() error {
	return m.validate(true)
}

func (m *Monitoring) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProducerDestinations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MonitoringValidationError{
						field:  fmt.Sprintf("ProducerDestinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MonitoringValidationError{
						field:  fmt.Sprintf("ProducerDestinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MonitoringValidationError{
					field:  fmt.Sprintf("ProducerDestinations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetConsumerDestinations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MonitoringValidationError{
						field:  fmt.Sprintf("ConsumerDestinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MonitoringValidationError{
						field:  fmt.Sprintf("ConsumerDestinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MonitoringValidationError{
					field:  fmt.Sprintf("ConsumerDestinations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MonitoringMultiError(errors)
	}

	return nil
}

// MonitoringMultiError is an error wrapping multiple validation errors
// returned by Monitoring.ValidateAll() if the designated constraints aren't met.
type MonitoringMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MonitoringMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MonitoringMultiError) AllErrors() []error { return m }

// MonitoringValidationError is the validation error returned by
// Monitoring.Validate if the designated constraints aren't met.
type MonitoringValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MonitoringValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MonitoringValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MonitoringValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MonitoringValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MonitoringValidationError) ErrorName() string { return "MonitoringValidationError" }

// Error satisfies the builtin error interface
func (e MonitoringValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitoring.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MonitoringValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MonitoringValidationError{}

// Validate checks the field values on Monitoring_MonitoringDestination with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *Monitoring_MonitoringDestination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Monitoring_MonitoringDestination with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// Monitoring_MonitoringDestinationMultiError, or nil if none found.
func (m *Monitoring_MonitoringDestination) ValidateAll() error {
	return m.validate(true)
}

func (m *Monitoring_MonitoringDestination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MonitoredResource

	if len(errors) > 0 {
		return Monitoring_MonitoringDestinationMultiError(errors)
	}

	return nil
}

// Monitoring_MonitoringDestinationMultiError is an error wrapping multiple
// validation errors returned by
// Monitoring_MonitoringDestination.ValidateAll() if the designated
// constraints aren't met.
type Monitoring_MonitoringDestinationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Monitoring_MonitoringDestinationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Monitoring_MonitoringDestinationMultiError) AllErrors() []error { return m }

// Monitoring_MonitoringDestinationValidationError is the validation error
// returned by Monitoring_MonitoringDestination.Validate if the designated
// constraints aren't met.
type Monitoring_MonitoringDestinationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Monitoring_MonitoringDestinationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Monitoring_MonitoringDestinationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Monitoring_MonitoringDestinationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Monitoring_MonitoringDestinationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Monitoring_MonitoringDestinationValidationError) ErrorName() string {
	return "Monitoring_MonitoringDestinationValidationError"
}

// Error satisfies the builtin error interface
func (e Monitoring_MonitoringDestinationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitoring_MonitoringDestination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Monitoring_MonitoringDestinationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Monitoring_MonitoringDestinationValidationError{}
