// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: google/api/metric.proto

package metric

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MetricDescriptor with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MetricDescriptor) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MetricDescriptor with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MetricDescriptorMultiError, or nil if none found.
func (m *MetricDescriptor) ValidateAll() error {
	return m.validate(true)
}

func (m *MetricDescriptor) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	for idx, item := range m.GetLabels() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MetricDescriptorValidationError{
						field:  fmt.Sprintf("Labels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MetricDescriptorValidationError{
						field:  fmt.Sprintf("Labels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MetricDescriptorValidationError{
					field:  fmt.Sprintf("Labels[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for MetricKind

	// no validation rules for ValueType

	// no validation rules for Unit

	// no validation rules for Description

	// no validation rules for DisplayName

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MetricDescriptorValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MetricDescriptorValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MetricDescriptorValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MetricDescriptorMultiError(errors)
	}

	return nil
}

// MetricDescriptorMultiError is an error wrapping multiple validation errors
// returned by MetricDescriptor.ValidateAll() if the designated constraints
// aren't met.
type MetricDescriptorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MetricDescriptorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MetricDescriptorMultiError) AllErrors() []error { return m }

// MetricDescriptorValidationError is the validation error returned by
// MetricDescriptor.Validate if the designated constraints aren't met.
type MetricDescriptorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MetricDescriptorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MetricDescriptorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MetricDescriptorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MetricDescriptorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MetricDescriptorValidationError) ErrorName() string { return "MetricDescriptorValidationError" }

// Error satisfies the builtin error interface
func (e MetricDescriptorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMetricDescriptor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MetricDescriptorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MetricDescriptorValidationError{}

// Validate checks the field values on Metric with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Metric) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Metric with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MetricMultiError, or nil if none found.
func (m *Metric) ValidateAll() error {
	return m.validate(true)
}

func (m *Metric) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Labels

	if len(errors) > 0 {
		return MetricMultiError(errors)
	}

	return nil
}

// MetricMultiError is an error wrapping multiple validation errors returned by
// Metric.ValidateAll() if the designated constraints aren't met.
type MetricMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MetricMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MetricMultiError) AllErrors() []error { return m }

// MetricValidationError is the validation error returned by Metric.Validate if
// the designated constraints aren't met.
type MetricValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MetricValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MetricValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MetricValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MetricValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MetricValidationError) ErrorName() string { return "MetricValidationError" }

// Error satisfies the builtin error interface
func (e MetricValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMetric.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MetricValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MetricValidationError{}

// Validate checks the field values on
// MetricDescriptor_MetricDescriptorMetadata with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MetricDescriptor_MetricDescriptorMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// MetricDescriptor_MetricDescriptorMetadata with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// MetricDescriptor_MetricDescriptorMetadataMultiError, or nil if none found.
func (m *MetricDescriptor_MetricDescriptorMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *MetricDescriptor_MetricDescriptorMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LaunchStage

	if all {
		switch v := interface{}(m.GetSamplePeriod()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MetricDescriptor_MetricDescriptorMetadataValidationError{
					field:  "SamplePeriod",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MetricDescriptor_MetricDescriptorMetadataValidationError{
					field:  "SamplePeriod",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSamplePeriod()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MetricDescriptor_MetricDescriptorMetadataValidationError{
				field:  "SamplePeriod",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetIngestDelay()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MetricDescriptor_MetricDescriptorMetadataValidationError{
					field:  "IngestDelay",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MetricDescriptor_MetricDescriptorMetadataValidationError{
					field:  "IngestDelay",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIngestDelay()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MetricDescriptor_MetricDescriptorMetadataValidationError{
				field:  "IngestDelay",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MetricDescriptor_MetricDescriptorMetadataMultiError(errors)
	}

	return nil
}

// MetricDescriptor_MetricDescriptorMetadataMultiError is an error wrapping
// multiple validation errors returned by
// MetricDescriptor_MetricDescriptorMetadata.ValidateAll() if the designated
// constraints aren't met.
type MetricDescriptor_MetricDescriptorMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MetricDescriptor_MetricDescriptorMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MetricDescriptor_MetricDescriptorMetadataMultiError) AllErrors() []error { return m }

// MetricDescriptor_MetricDescriptorMetadataValidationError is the validation
// error returned by MetricDescriptor_MetricDescriptorMetadata.Validate if the
// designated constraints aren't met.
type MetricDescriptor_MetricDescriptorMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MetricDescriptor_MetricDescriptorMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MetricDescriptor_MetricDescriptorMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MetricDescriptor_MetricDescriptorMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MetricDescriptor_MetricDescriptorMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MetricDescriptor_MetricDescriptorMetadataValidationError) ErrorName() string {
	return "MetricDescriptor_MetricDescriptorMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e MetricDescriptor_MetricDescriptorMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMetricDescriptor_MetricDescriptorMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MetricDescriptor_MetricDescriptorMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MetricDescriptor_MetricDescriptorMetadataValidationError{}
